### ISSUE TITLE
Lose entire RH side of Manager page

### ISSUE THREAD

**Issue by gissirob** [DESIGNfromWITHIN/Flexibility4Issues#10]
I created a brand new 2.2.8 site and did nothing before installing Flexibility4. After successful install, and before I did anything, I updated Articles to 1.6.8.

I then went to modify the home page as per your instructions. After clicking on it, the RH panel of Manager disappeared and I can't get it back. Manager menus are still present, but selecting anything from the menu results in an empty RH panel.

Resource tree is still present and is fully navigable. Clicking on any resource results in a still blank RH panel.

**Comment by DESIGNfromWITHIN** [comment]
Mmm strange... Anything in the error logs?

Btw, I am working ahrd on a update that should fix these install of packages issues...

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed...

**Comment by gissirob** [comment]
Hi Menno,

Afraid I had the same problem. As I could not update your package (a bit
hard without being able to see the manager) I created a new install and
loaded your new package (flexibility4-1.0.3-rc.transport). After
installation, the first thing I did was click on the Home resource, and
then everything went blank again in the RH panel.

I'm happy to continue to work with you on this, but I have other deadlines
so I won't be spending any more time investigating for myself. If you have
specific questions, or want me to try something, please let me know
(although it might be a bit hard with a blank manager panel). Otherwise
I'll check back when there is a full release version.

Robert.

PS: I'm using an Ubuntu 12.04 VM and Firefox 17.01 if that's of any help.

**Comment by DESIGNfromWITHIN** [comment]
Mmmm strange, I also never used tested Ubuntu...
Does MODX work fine on your system before you install Flexibility 1.0.3-rc?

I guess you can not post the error.log?

**Comment by gissirob** [comment]
It has previously worked fine for other test sites (this is my test
machine). However to be sure I will do a fresh install without Flexibility
and check.

No, the error log is not available.

**Comment by gissirob** [comment]
Just tried a fresh install but no Flexibility. No problems. Everything is
there and working properly. So I re-installed Flexibility and captured the
console (see below). Hope this is helpful.

---

Console running...
Attempting to install package with signature: flexibility4-1.0.3-rc
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Could not find Element and/or Property Set Contact page - PropertySet2
Could not create target directory /var/www/blog2/manager/assets/components
Could not copy
/var/www/blog2/core/packages/ace-1.4.0-pl/modPlugin/6dc0881868bd0240ba3f00009df786eb/0/
to /var/www/blog2/manager/assets/components/ace
Attempting to preserve files at /var/www/blog2/core/components/ace into
archive
/var/www/blog2/core/packages/ace-1.4.0-pl/modPlugin/6dc0881868bd0240ba3f00009df786eb.1.preserved.zip
Attempting to set which_element_editor setting to Ace.
Error adding field quipComment->name: Array ( [0] => 42S21 [1] => 1060 [2]
=> Duplicate column name 'name' )
Error adding field quipComment->email: Array ( [0] => 42S21 [1] => 1060 [2]
=> Duplicate column name 'email' )
Error adding field quipComment->website: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'website' )
Error adding field quipComment->resource: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'resource' )
Error adding field quipComment->idprefix: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'idprefix' )
Error adding field quipComment->existing_params: Array ( [0] => 42S21 [1]
=> 1060 [2] => Duplicate column name 'existing_params' )
Error adding index resource to quipComment: Array ( [0] => 42000 [1] =>
1061 [2] => Duplicate key name 'resource' )
Error adding field quipComment->ip: Array ( [0] => 42S21 [1] => 1060 [2] =>
Duplicate column name 'ip' )
Error adding field quipComment->rank: Array ( [0] => 42S21 [1] => 1060 [2]
=> Duplicate column name 'rank' )
Error adding field quipComment->approvedby: Array ( [0] => 42S21 [1] =>
1060 [2] => Duplicate column name 'approvedby' )
Error adding field quipComment->deleted: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'deleted' )
Error adding field quipComment->deletedon: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'deletedon' )
Error adding field quipComment->deletedby: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'deletedby' )
Error adding index approvedby to quipComment: Array ( [0] => 42000 [1] =>
1061 [2] => Duplicate key name 'approvedby' )
Error adding index deleted to quipComment: Array ( [0] => 42000 [1] => 1061
[2] => Duplicate key name 'deleted' )
Error adding index deletedby to quipComment: Array ( [0] => 42000 [1] =>
1061 [2] => Duplicate key name 'deletedby' )
Error adding field quipThread->quip_call_params: Array ( [0] => 42S21 [1]
=> 1060 [2] => Duplicate column name 'quip_call_params' )
Error adding field quipThread->quipreply_call_params: Array ( [0] => 42S21
[1] => 1060 [2] => Duplicate column name 'quipreply_call_params' )
Could not load class: quipNotifyComment from mysql.quipnotifycomment.
Could not load class: quipNotifyComment from mysql.quipnotifycomment.
Error removing field Article->articles_container: Array ( [0] => 42000 [1]
=> 1091 [2] => Can't DROP 'articles_container'; check that column/key
exists )
Error removing field Article->articles_container_settings: Array ( [0] =>
42000 [1] => 1091 [2] => Can't DROP 'articles_container_settings'; check
that column/key exists )
Error adding field cgSetting->sortorder: Array ( [0] => 42S21 [1] => 1060
[2] => Duplicate column name 'sortorder' )
Error adding field cgGroup->sortorder: Array ( [0] => 42S21 [1] => 1060 [2]
=> Duplicate column name 'sortorder' )
Skipping vehicle object of class modSystemSetting (data object exists and
cannot be upgraded); criteria: Array ( [key] => xhtml_urls )
Created table `blog2_gallery_items` SQL: CREATE TABLE `blog2_gallery_items`
(`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(100) NOT
NULL DEFAULT '', `filename` VARCHAR(255) NOT NULL DEFAULT '', `description`
TEXT NULL, `mediatype` VARCHAR(40) NOT NULL DEFAULT 'image', `url` TEXT
NULL, `createdon` DATETIME NULL, `createdby` INT(10) unsigned NOT NULL
DEFAULT '0', `active` TINYINT(1) unsigned NOT NULL DEFAULT '0', `duration`
VARCHAR(40) NOT NULL DEFAULT '', `streamer` TEXT NULL, `watermark_pos`
VARCHAR(10) NOT NULL DEFAULT 'tl', PRIMARY KEY (`id`), INDEX `createdby`
(`createdby`)) ENGINE=MyISAM
Created table `blog2_gallery_albums` SQL: CREATE TABLE
`blog2_gallery_albums` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT,
`parent` INT(10) unsigned NOT NULL DEFAULT '0', `name` VARCHAR(255) NOT
NULL DEFAULT '', `description` TEXT NULL, `createdon` DATETIME NULL,
`createdby` INT(10) unsigned NOT NULL DEFAULT '0', `rank` INT(10) unsigned
NOT NULL DEFAULT '0', `active` TINYINT(1) unsigned NOT NULL DEFAULT '0',
`prominent` TINYINT(1) unsigned NOT NULL DEFAULT '0', `watermark`
VARCHAR(255) NOT NULL DEFAULT '', PRIMARY KEY (`id`), INDEX `parent`
(`parent`), INDEX `name` (`name`), INDEX `createdby` (`createdby`))
ENGINE=MyISAM
Created table `blog2_gallery_album_items` SQL: CREATE TABLE
`blog2_gallery_album_items` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT,
`item` INT(10) unsigned NOT NULL DEFAULT '0', `album` INT(10) unsigned NOT
NULL DEFAULT '0', `rank` INT(10) unsigned NOT NULL DEFAULT '0', PRIMARY KEY
(`id`), INDEX `item` (`item`), INDEX `album` (`album`)) ENGINE=MyISAM
Created table `blog2_gallery_album_contexts` SQL: CREATE TABLE
`blog2_gallery_album_contexts` (`id` INTEGER unsigned NOT NULL
AUTO_INCREMENT, `album` INT(10) unsigned NOT NULL DEFAULT '0',
`context_key` VARCHAR(100) NOT NULL DEFAULT 'web', PRIMARY KEY (`id`),
INDEX `album` (`album`), INDEX `context_key` (`context_key`)) ENGINE=MyISAM
Created table `blog2_gallery_tags` SQL: CREATE TABLE `blog2_gallery_tags`
(`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `item` INT(10) unsigned NOT
NULL DEFAULT '0', `tag` VARCHAR(255) NOT NULL DEFAULT '', PRIMARY KEY
(`id`), INDEX `item` (`item`), INDEX `tag` (`tag`)) ENGINE=MyISAM
xPDOVehicle validator failed: type php
(/var/www/blog2/core/packages/flexibility4-1.0.3-rc/xPDOTransportVehicle/aeef5922cde5a1f1e777d4f4f6808535.validate.getresources.validator)
Could not validate vehicle: Array ( [license] => GNU GENERAL PUBLIC LICENSE
Version 2, June 1991 -------------------------- Copyright (C) 1989, 1991
Free Software Foundation, Inc. 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed. Preamble --------
The licenses for most software are designed to take away your freedom to
share and change it. By contrast, the GNU General Public License is
intended to guarantee your freedom to share and change free software--to
make sure the software is free for all its users. This General Public
License applies to most of the Free Software Foundation's software and to
any other program whose authors commit to using it. (Some other Free
Software Foundation software is covered by the GNU Library General Public
License instead.) You can apply it to your programs, too. When we speak of
free software, we are referring to freedom, not price. Our General Public
Licenses are designed to make sure that you have the freedom to distribute
copies of free software (and charge for this service if you wish), that you
receive source code or can get it if you want it, that you can change the
software or use pieces of it in new free programs; and that you know you
can do these things. To protect your rights, we need to make restrictions
that forbid anyone to deny you these rights or to ask you to surrender the
rights. These restrictions translate to certain responsibilities for you if
you distribute copies of the software, or if you modify it. For example, if
you distribute copies of such a program, whether gratis or for a fee, you
must give the recipients all the rights that you have. You must make sure
that they, too, receive or can get the source code. And you must show them
these terms so they know their rights. We protect your rights with two
steps: (1) copyright the software, and (2) offer you this license which
gives you legal permission to copy, distribute and/or modify the software.
Also, for each author's protection and ours, we want to make certain that
everyone understands that there is no warranty for this free software. If
the software is modified by someone else and passed on, we want its
recipients to know that what they have is not the original, so that any
problems introduced by others will not reflect on the original authors'
reputations. Finally, any free program is threatened constantly by software
patents. We wish to avoid the danger that redistributors of a free program
will individually obtain patent licenses, in effect making the program
proprietary. To prevent this, we have made it clear that any patent must be
licensed for everyone's free use or not licensed at all. The precise terms
and conditions for copying, distribution and modification follow. GNU
GENERAL PUBLIC LICENSE TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND
MODIFICATION
--------------------------------------------------------------- 0. This
License applies to any program or other work which contains a notice placed
by the copyright holder saying it may be distributed under the terms of
this General Public License. The "Program", below, refers to any such
program or work, and a "work based on the Program" means either the Program
or any derivative work under copyright law: that is to say, a work
containing the Program or a portion of it, either verbatim or with
modifications and/or translated into another language. (Hereinafter,
translation is included without limitation in the term "modification".)
Each licensee is addressed as "you". Activities other than copying,
distribution and modification are not covered by this License; they are
outside its scope. The act of running the Program is not restricted, and
the output from the Program is covered only if its contents constitute a
work based on the Program (independent of having been made by running the
Program). Whether that is true depends on what the Program does. 1. You may
copy and distribute verbatim copies of the Program's source code as you
receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice and
disclaimer of warranty; keep intact all the notices that refer to this
License and to the absence of any warranty; and give any other recipients
of the Program a copy of this License along with the Program. You may
charge a fee for the physical act of transferring a copy, and you may at
your option offer warranty protection in exchange for a fee. 2. You may
modify your copy or copies of the Program or any portion of it, thus
forming a work based on the Program, and copy and distribute such
modifications or work under the terms of Section 1 above, provided that you
also meet all of these conditions: a) You must cause the modified files to
carry prominent notices stating that you changed the files and the date of
any change. b) You must cause any work that you distribute or publish, that
in whole or in part contains or is derived from the Program or any part
thereof, to be licensed as a whole at no charge to all third parties under
the terms of this License. c) If the modified program normally reads
commands interactively when run, you must cause it, when started running
for such interactive use in the most ordinary way, to print or display an
announcement including an appropriate copyright notice and a notice that
there is no warranty (or else, saying that you provide a warranty) and that
users may redistribute the program under these conditions, and telling the
user how to view a copy of this License. (Exception: if the Program itself
is interactive but does not normally print such an announcement, your work
based on the Program is not required to print an announcement.) These
requirements apply to the modified work as a whole. If identifiable
sections of that work are not derived from the Program, and can be
reasonably considered independent and separate works in themselves, then
this License, and its terms, do not apply to those sections when you
distribute them as separate works. But when you distribute the same
sections as part of a whole which is a work based on the Program, the
distribution of the whole must be on the terms of this License, whose
permissions for other licensees extend to the entire whole, and thus to
each and every part regardless of who wrote it. Thus, it is not the intent
of this section to claim rights or contest your rights to work written
entirely by you; rather, the intent is to exercise the right to control the
distribution of derivative or collective works based on the Program. In
addition, mere aggregation of another work not based on the Program with
the Program (or with a work based on the Program) on a volume of a storage
or distribution medium does not bring the other work under the scope of
this License. 3. You may copy and distribute the Program (or a work based
on it, under Section 2) in object code or executable form under the terms
of Sections 1 and 2 above provided that you also do one of the following:
a) Accompany it with the complete corresponding machine-readable source
code, which must be distributed under the terms of Sections 1 and 2 above
on a medium customarily used for software interchange; or, b) Accompany it
with a written offer, valid for at least three years, to give any third
party, for a charge no more than your cost of physically performing source
distribution, a complete machine-readable copy of the corresponding source
code, to be distributed under the terms of Sections 1 and 2 above on a
medium customarily used for software interchange; or, c) Accompany it with
the information you received as to the offer to distribute corresponding
source code. (This alternative is allowed only for noncommercial
distribution and only if you received the program in object code or
executable form with such an offer, in accord with Subsection b above.) The
source code for a work means the preferred form of the work for making
modifications to it. For an executable work, complete source code means all
the source code for all modules it contains, plus any associated interface
definition files, plus the scripts used to control compilation and
installation of the executable. However, as a special exception, the source
code distributed need not include anything that is normally distributed (in
either source or binary form) with the major components (compiler, kernel,
and so on) of the operating system on which the executable runs, unless
that component itself accompanies the executable. If distribution of
executable or object code is made by offering access to copy from a
designated place, then offering equivalent access to copy the source code
from the same place counts as distribution of the source code, even though
third parties are not compelled to copy the source along with the object
code. 4. You may not copy, modify, sublicense, or distribute the Program
except as expressly provided under this License. Any attempt otherwise to
copy, modify, sublicense or distribute the Program is void, and will
automatically terminate your rights under this License. However, parties
who have received copies, or rights, from you under this License will not
have their licenses terminated so long as such parties remain in full
compliance. 5. You are not required to accept this License, since you have
not signed it. However, nothing else grants you permission to modify or
distribute the Program or its derivative works. These actions are
prohibited by law if you do not accept this License. Therefore, by
modifying or distributing the Program (or any work based on the Program),
you indicate your acceptance of this License to do so, and all its terms
and conditions for copying, distributing or modifying the Program or works
based on it. 6. Each time you redistribute the Program (or any work based
on the Program), the recipient automatically receives a license from the
original licensor to copy, distribute or modify the Program subject to
these terms and conditions. You may not impose any further restrictions on
the recipients' exercise of the rights granted herein. You are not
responsible for enforcing compliance by third parties to this License. 7.
If, as a consequence of a court judgment or allegation of patent
infringement or for any other reason (not limited to patent issues),
conditions are imposed on you (whether by court order, agreement or
otherwise) that contradict the conditions of this License, they do not
excuse you from the conditions of this License. If you cannot distribute so
as to satisfy simultaneously your obligations under this License and any
other pertinent obligations, then as a consequence you may not distribute
the Program at all. For example, if a patent license would not permit
royalty-free redistribution of the Program by all those who receive copies
directly or indirectly through you, then the only way you could satisfy
both it and this License would be to refrain entirely from distribution of
the Program. If any portion of this section is held invalid or
unenforceable under any particular circumstance, the balance of the section
is intended to apply and the section as a whole is intended to apply in
other circumstances. It is not the purpose of this section to induce you to
infringe any patents or other property right claims or to contest validity
of any such claims; this section has the sole purpose of protecting the
integrity of the free software distribution system, which is implemented by
public license practices. Many people have made generous contributions to
the wide range of software distributed through that system in reliance on
consistent application of that system; it is up to the author/donor to
decide if he or she is willing to distribute software through any other
system and a licensee cannot impose that choice. This section is intended
to make thoroughly clear what is believed to be a consequence of the rest
of this License. 8. If the distribution and/or use of the Program is
restricted in certain countries either by patents or by copyrighted
interfaces, the original copyright holder who places the Program under this
License may add an explicit geographical distribution limitation excluding
those countries, so that distribution is permitted only in or among
countries not thus excluded. In such case, this License incorporates the
limitation as if written in the body of this License. 9. The Free Software
Foundation may publish revised and/or new versions of the General Public
License from time to time. Such new versions will be similar in spirit to
the present version, but may differ in detail to address new problems or
concerns. Each version is given a distinguishing version number. If the
Program specifies a version number of this License which applies to it and
"any later version", you have the option of following the terms and
conditions either of that version or of any later version published by the
Free Software Foundation. If the Program does not specify a version number
of this License, you may choose any version ever published by the Free
Software Foundation. 10. If you wish to incorporate parts of the Program
into other free programs whose distribution conditions are different, write
to the author to ask for permission. For software which is copyrighted by
the Free Software Foundation, write to the Free Software Foundation; we
sometimes make exceptions for this. Our decision will be guided by the two
goals of preserving the free status of all derivatives of our free software
and of promoting the sharing and reuse of software generally. NO WARRANTY
----------- 11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO
WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT
WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM
PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR
CORRECTION. 12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO
IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY
AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR
DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL
DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING
BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES
SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE
WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN
ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. --------------------------- END
OF TERMS AND CONDITIONS [readme] => Flexibility 4
http://flexibilitymodx.com/ ---------------------------- Flexibility -
Fully functional MODX Revolution website. Quickstart projects by creating a
fully working MODX Revolution website with just one package! Flexibility
includes navigation, search, blog, client setting, templates, template
variables and more. This package is meant to be used once to quick-start
MODX website projects. It will install a lot of things and provide a nice
responsive MODX website based on the Foundation framework from ZURB.
---------------------------- !!! ATTENTION !!! ----------------------------
If you change or edit any Chunk, Snippet, Template Variable or Plugin that
was included in the Flexibility package, please rename it! Or it will be
overwritten on any future updates. Any needed packages (like Wayfinder)
will be installed automatically by the Flexibility package. You will be
able to update and edit any sub-packages at a later date. ABOUT
"Flexibility 4" is a HTML5/CSS3/jQuery based frontend MODX Revolution
template based on the "Foundation 4" (http://foundation.zurb.com/). With
this package you will have a fully functional website with a dropdown nav,
contact form, slider and a image gallery. "Flexibility 4" is designed and
coded by Menno Pietersen Portfolio & blog: DESIGNfromWITHIN
http://designfromwithin.com Twitter: MennoPP
https://twitter.com/MennoPP---------------------------- MANUAL INSTALL

---

Install MODX Revolution on your website. - Download the package and upload
the "flexibility4-x.x.x-x.transport.zip" file to "/core/packages/" (You
only need the transport.zip file, do not unzip it yourself) - Install the
"Flexibility 4" package: Go to "System" > "Package Management" > "Add New
Package" > "Search Locally for Packages" > "Yes". (to be sure clear your
cache > "Site" > "Clear Cache") ---------------------------- ADDING AND
CHANGING CONTENT ---------------------------- - Simply add resources/pages
as you need annd assign the template you want to use. After selecting a
template you will find template specific options under the 'Template
Variables' tab. - Content can be updated using Tiny MCE, the active CSS
styles will be shown automatically and easy to select style classes are
selectable via the 'Styles' button. ---------------------------- CHOOSING
THE NAVIGATION TYPE ---------------------------- - Under system settings >
(filter for 'flexibility4') > 'Use Foundation top bar for main navigation'
you can select wich type of navigation you want.
---------------------------- UPDATE INSTRUCTIONS:
---------------------------- All sub-packages (like Wayfinder) are
installed by Flexibility and you will be able to remove/update each
sub-package under "System" > "Package Management". You can update the
package via package installer, Flexibility will NOT override excisiting
Resources. ---------------------------- CREDITS, SUPPORTERS AND
CONTRIBUTORS: ---------------------------- - http://foundation.zurb.com/ -
http://html5boilerplate.com/ (not used but got me started....) - The MODX
Revolution team for the whole MODX system - Anselm Hannemann (
http://anselm.novolo.de/) for the MODX Boilerplate - The MODX community for
all the great tips and support! - Bob Ray (http://bobsguides.com/) for the
amazing MyComponent package ---------------------------- BUGS and FEATURE
REQUESTS: ---------------------------- Please post on GitHub:
https://github.com/DESIGNfromWITHIN/Flexibility4Issues/issues [changelog]
=> Changelog for Flexibility flexibility4-1.0.3-rc.transport (23 juli 2013)
==================================== - Added Page title to Foundation top
bar navigation - Replaced ckeditor with Tiny MCE, linked CSS styles and
added button style selectors to Tiny MCE - Updated readme
flexibility4-1.0.2-rc.transport (23 juli 2013)
==================================== - Added working Foundation top bar
navigation + navigation option - Under system settings > (filter for
'flexibility4') > 'Use Foundation top bar for main navigation' you can
select wich type of navigation you want flexibility4-1.0.0-rc.transport (22
juli 2013) ==================================== - 100% rebuilt using Bob
Ray's MyComponent 3.1.1-pl - Seperated template content and core files,
seperate package with demo content available soon
flexibility4-0.0.2-rc.transport (22 march 2013)
==================================== - Fixed TV's not being assigned to
templates (Thanks Jörg Lippmann @donalbain_de) - Removed the Sidebar TV
from the page without sidebar - Added ios-orientationchange-fix.js (Thanks
@PgnFrsh) flexibility4-0.0.1-rc.transport (21 march 2013)
==================================== - Huge update to v4! - Updates without
losing content - Removed the installation of default resources (this is not
the 'MODX way') - Lexicons added - Articles added - MIGX slider items added
- Gallery added - Search improved - Google sitemap added - Version X added
- Ace added - Replaced Tiny MCE with ckeditor - Client Config added (needs
  to be configured) - PHPthunbsUp added and used in the image gallery -
  Responsive lightbox added - Added page templates with left and right
  sidebar flexibility-3.0.6-rc.transport (18 januari 2013)
  ==================================== - Added a mobile input navigation for
  smaller screens - The full template should now be faster and more
  streamlined flexibility-3.0.5-rc.transport (12 december 2012)
  ==================================== - Changed UPDATE_OBJECT back to TRUE
  (xPDOTransport::UPDATE_OBJECT => true), this was not working... Will try to
  create a seperate update package to Flexibility.
  flexibility-3.0.4-rc.transport (4 december 2012)
  ==================================== - Fixed Slider MIGX items (again)
  flexibility-3.0.3-rc.transport (14 november 2012)
  ==================================== - Fixed Slider MIGX item, should work
  fine now flexibility-3.0.2-rc.transport (6 november 2012)
  ==================================== - Flexibility is a Release Candidate
  now! - Updated to Foundation 3.2 - Changed UPDATE_OBJECT to FALSE
  (xPDOTransport::UPDATE_OBJECT => false), should prevent overwriting content
  on existing Flexibility installs. - Added slide content - Updated formit to
  2.1.2-pl - Updated getresources to 1.5.1-pl - Updated migx to 2.3.2-pl
  flexibility-3.0.1-alpha.transport (3 september 2012)
  ==================================== - Updated to Foundation 3.1.1 - Tested
  for MODX Revolution 2.2.5-pl flexibility-3.0.0-alpha.transport (16 august
  2012) ==================================== - Updated to Foundation 3.0
  flexibility-2.1.1-alpha.transport (16 august 2012)
  ==================================== - Updated FormIt to
  formit-2.1.1-pl.transport - Updated Gallery to gallery-1.5.2-pl.transport -
  Updated GetResources to getresources-1.5.0-pl.transport - Updated MIGX to
  migx-2.3.0-pl.transport - Updated SimpleSearch to
  simplesearch-1.6.0-pl.transport - Updated TinyMCE to
  tinymce-4.3.3-pl.transport - Updated TinyMCE to tinymce-4.3.3-pl.transport
  flexibility-2.1.0-alpha.transport (2 august 2012)
  ==================================== - Fixed the Image slider (many thanks
  to: Designforge) - Updated MIGX to migx-2.2.3-pl.transport
  flexibility-2.0.9-alpha.transport (7 july 2012)
  ==================================== - Added the first commit adding the
  In-Field-Labels jquery plugin (many thanks to: frogabog)
  flexibility-2.0.8-alpha.transport (5 june 2012)
  ==================================== - Fixed the php thumb bug and gallery
- Added the latest version of fancybox.js - Updated packages Articles to
  articles-1.6.1-pl.transport - Updated packages Simple Search to
  simplesearch-1.6.0-pl.transport - Updated packages MIGX to
  migx-2.0.1-pl.transport - Updated packages Gallery to
  gallery-1.5.0-pl.transport - Added "'gallery.thumbs_prepend_site_url' =>
  true" setting to the install - Added "'phpthumb_allow_src_above_docroot' =>
  true" setting to the install flexibility-2.0.6-alpha.transport (11 march
  2012) ==================================== - Changed TV order - Removed
  unwanted code - Added Public License - Remove includeTemplate code, now
  using Media Sources - Updated packages (FormIt, getResources, simplesearch,
  TinyMCE) - Updated Foundation Framework to 2.2 - Fixed small dropdown issue
  flexibility-2.0.5-alpha.transport (8 febuary 2012)
  ==================================== - Fixed sub-page-2 bug (thanks Showa!)
  flexibility-2.0.4-alpha.transport (5-2-2012)
  ==================================== - Template variables are now added to
  the correct template. - Ready for ALPHA testing!
  flexibility-2.0.3-beta.transport (4 febuary 2012)
  ==================================== - Using just one category now. - Fixed
  MIGX bug. flexibility-2.0.2-beta.transport (17 december 2011)
  ==================================== - Added MIGX TV's for adding slides to
  the image slider. flexibility-2.0.1-beta.transport (13 december 2011)
  ==================================== - First version online!
  [setup-options] => Array ( ) [signature] =>
  aeef5922cde5a1f1e777d4f4f6808535 [initialConfig] => [object Object] [text]
  => Continue [id] => package-install-btn [hidden] => false [handler] =>
  function (va){var g=Ext.getCmp('modx-package-grid');if(!g)return false;var
  r=g.menu.record.data?g.menu.record.data:g.menu.record;var
  topic='/workspace/package/install/'+r.signature+'/';this.loadConsole(Ext.getBody(),topic);va=va||{};Ext.apply(va,{action:'install',signature:r.signature,register:'mgr',topic:topic});var
  c=this.console;MODx.Ajax.request({url:MODx.config.connectors_url+'workspace/packages.php',params:va,listeners:{'success':{fn:function(){this.activate();Ext.getCmp('modx-package-grid').refresh();},scope:this},'failure':{fn:function(){this.activate();},scope:this}}});}
  [scope] => [object Object] [minWidth] => 75 [removeMode] => container
  [hideParent] => true [events] => [object Object] [ownerCt] => [object
  Object] [container] => [object Object] [rendered] => true [template] =>
  [object Object] [btnEl] => [object Object] [mons] => [object Object] [el]
  => [object Object] [icon] => [iconCls] => [boxReady] => true [lastSize] =>
  [object Object] [useSetClass] => true [oldCls] => x-btn-noicon [doc] =>
  [object Object] [monitoringMouseOver] => true [action] => install
  [register] => mgr [topic] =>
  /workspace/package/install/flexibility4-1.0.3-rc/ [HTTP_MODAUTH] =>
  modx51eed479c74d29.79826194_151eed502948579.11489937 [package_action] => 0
  [vehicle_package] => transport [vehicle_class] => xPDOTransportVehicle
  [class] => xPDOTransportVehicle [guid] => de13df82bbf2ed1d94cf10c3502357c8
  [native_key] => de13df82bbf2ed1d94cf10c3502357c8 [filename] =>
  xPDOTransportVehicle/aeef5922cde5a1f1e777d4f4f6808535.vehicle [namespace]
  => flexibility4 [object] => Array ( [source] =>
  flexibility4-1.0.3-rc/xPDOTransportVehicle/aeef5922cde5a1f1e777d4f4f6808535/
  [target] => return MODX_CORE_PATH . 'packages/'; [name] =>
  getresources-1.6.0-pl.transport.zip ) [resolve] => Array ( [0] => Array (
  [type] => php [body] =>
  {"source":"flexibility4-1.0.3-rc\/xPDOTransportVehicle\/aeef5922cde5a1f1e777d4f4f6808535.resolve.getresources.resolver","type":"php","name":"resolve.getresources"}
  ) ) [validate] => Array ( [0] => Array ( [type] => php [body] =>
  {"source":"flexibility4-1.0.3-rc\/xPDOTransportVehicle\/aeef5922cde5a1f1e777d4f4f6808535.validate.getresources.validator","type":"php","name":"validate.getresources"}
  ) ) [package] => )
  Attempting to set which_editor setting to TinyMCE.
  Attempting to set use_editor setting to on.
  Attempting to fix forced_root_block setting for TinyMCE.
  Starting snapshot process for selected objects...
  Added VersionX Resources dashboard widget to your MODX installation. To use
  it, add it to a dashboard.
  Successfully installed package flexibility4-1.0.3-rc

---

Once Flexibility was install the first time I clicked on a menu, the RH
panel disappeared.

Robert.

**Comment by DESIGNfromWITHIN** [comment]
Could you try the latest 1.1.0.pl version?

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed, please let me know if it is not...

**Comment by gissirob** [comment]
Menno, on vacation for the next week. Will try once I get back home.

**Comment by okinol** [comment]
Guess, I need to reopen :-(. I did a complete fresh install of modx_revo2.2.9 on a SUSE Linux 11.4 server. Actually there has been an issue during install by package management, telling me, it can't create anything under /manager/assets or so (latest release 1.1.1 of Flexibility4, as I remember). Okay, I'll deal with that on my next try :-). 

But the problem remains the same. After "installation was susccessful", none of the RH pages of manager frontend will open. Login and logout reproduce this behavior...

**Comment by okinol** [comment]
I resolved the problem by manually installing. I think it is a problem with initial folder rights for installation within the install routine ...
